#define BUILD_INCREMENT 259
#define LUPUS_STRINGIFY(x) #x
#define LUPUS_XSTRINGIFY(x) LUPUS_STRINGIFY(x)

#define LUPUS_CORE_MAJOR 0
#define LUPUS_CORE_MINOR 1
#define LUPUS_CORE_BUILD 0
#define LUPUS_CORE_REVISION BUILD_INCREMENT
#define LUPUS_STRINGIFY(x) #x

#define LUPUS_CORE_VERSION LUPUS_CORE_MAJOR,LUPUS_CORE_MINOR,LUPUS_CORE_BUILD,LUPUS_CORE_REVISION
#define LUPUS_CORE_VERSION_STRING LUPUS_XSTRINGIFY(LUPUS_CORE_MAJOR) "." LUPUS_XSTRINGIFY(LUPUS_CORE_MINOR) "." LUPUS_XSTRINGIFY(LUPUS_CORE_BUILD) "." LUPUS_XSTRINGIFY(LUPUS_CORE_REVISION)
